project_id = "muwiuiwtyodefmszrjjf"

[functions.drug-interaction-checker]
verify_jwt = true

[functions.ocr-processor]
verify_jwt = true

[functions.pill-identifier]
verify_jwt = true

[functions.generate-invite-code]
verify_jwt = true

[functions.accept-invite-code]
verify_jwt = true

[functions.disconnect-caregiver]
verify_jwt = true